"""
Class for serial communication. Mostly generated by ChatGPT.
Author: Rainer Meyer, rot.meyer494@gmail.com
"""

from PyQt6.QtCore import QObject, pyqtSignal, QTimer
import serial
import serial.tools.list_ports
import time
import threading
from collections import deque


class GCSerial(QObject):

    connected = pyqtSignal(str, int)
    disconnected = pyqtSignal()

    ports_changed = pyqtSignal(list)
    line_received = pyqtSignal(str)
    status_received = pyqtSignal(str)
    error_received = pyqtSignal(str)
    alarm_received = pyqtSignal(str)

    def __init__(self):

        super().__init__()

        self._ser = None
        self._running = False

        self._tx_thread = None
        self._rx_thread = None

        self._queue = deque()
        self._pending_lengths = deque()
        self._bytes_in_flight = 0

        self._queue_lock = threading.Lock()
        self._serial_lock = threading.Lock()

        self._state_cv = threading.Condition()

        self._poll_timer = QTimer()

        self._poll_timer.timeout.connect(self.poll_status)

    @property
    def is_connected(self):
        if self._ser:
            return self._ser.is_open
        return False

    def connect(self, port, baud=115200) -> bool:
        self._ser = serial.Serial(port, baud, timeout=0.5, write_timeout=0.5)
        if not self._ser:
            return False
        time.sleep(2)
        self._ser.reset_input_buffer()
        self._ser.reset_output_buffer()
        self._running = True

        self._tx_thread = threading.Thread(target=self._tx_loop, daemon=True)
        self._rx_thread = threading.Thread(target=self._rx_loop, daemon=True)

        self._tx_thread.start()
        self._rx_thread.start()

        self._poll_timer.start(100)
        self.connected.emit(port, baud)
        return True

    def disconnect(self):
        self._running = False
        self._poll_timer.stop()

        # Wake up the TX thread if it's waiting on the Condition Variable
        with self._state_cv:
            self._state_cv.notify_all()

        # Close the port first! This forces the blocking rx read to immediately crash and exit
        if self._ser and self._ser.is_open:
            with self._serial_lock:
                self._ser.close()

        if self._tx_thread:
            self._tx_thread.join()
        if self._rx_thread:
            self._rx_thread.join()

        print("Disconnected")
        self.disconnected.emit()

    def send(self, cmd):
        with self._queue_lock:
            self._queue.append(cmd.strip())
            # print(f"Added to buffer: {cmd}")

        with self._state_cv:
            self._state_cv.notify()

    def send_realtime(self, cmd):
        with self._serial_lock:
            n = self._ser.write(cmd.encode("ascii"))
            #self._ser.flush()
            #print(f"Sent realtime: {cmd}, bytes={n}")

    def _tx_loop(self):
        while self._running:
            with self._state_cv:
                self._state_cv.wait_for(lambda: (self._queue and self._can_send()) or not self._running)

            if not self._running:
                break

            with self._queue_lock:
                cmd = self._queue.popleft()
                #print(f"Popped from buffer: {cmd}")

            self._send_gcode(cmd)

    def _can_send(self):
        if not self._queue:
            # print(f"Buffer empty")
            return False

        cmd = self._queue[0]
        n = len(cmd) + 1
        can_send = self._bytes_in_flight + n < 117
        #print(f"Can send={can_send}, bytes_in_flight={self._bytes_in_flight}")
        return can_send

    def _send_gcode(self, cmd):
        n = len(cmd) + 1

        with self._serial_lock:
            self._ser.write((cmd + '\n').encode("ascii"))
            # self._ser.flush()
            #print(f"Sent: {cmd}")

        with self._state_cv:
            self._bytes_in_flight += n
            self._pending_lengths.append(n)

            # TODO: Check this
            self._state_cv.notify()

    def _rx_loop(self):
        while self._running:
            try:
                line = self._ser.readline()
                if not line:
                    # print(f"No line")
                    continue
                line = line.decode('ascii').strip()
                #print(f"Received line: {line}")

            except (serial.SerialException, OSError) as e:
                print(f"Serial connection lost: {e}")
                break

            self._process_line(line)

    def _process_line(self, line):
        self.line_received.emit(line)

        if line.startswith('ok'):
            self._ack()
            return

        if line.startswith('error'):
            self._ack()
            self.error_received.emit(line)
            return

        if line.startswith('<'):
            self.status_received.emit(line)
            return

        if line.startswith("ALARM"):
            self.alarm_received.emit(line)

    def _ack(self):
        with self._state_cv:
            if self._pending_lengths:
                n = self._pending_lengths.popleft()
                self._bytes_in_flight -= n
            self._state_cv.notify()

    def poll_status(self):
        if not self._running or not self._ser or not self._ser.is_open:
            return
        self.send_realtime("?")

    def scan_ports(self):
        ports = [p.device for p in serial.tools.list_ports.comports()]
        self.ports_changed.emit(ports)
        return ports
